all: memdumper readaddress stacktest

memdumper:
	g++ -o binaries/app_memdumper memdumper.cpp

readaddress:
	g++ -o binaries/app_readaddress readaddress.cpp

stacktest:
	g++ -o binaries/app_stacktest stacktest.cpp
